"""
Service Port Registry — Single Source of Truth (Plan 144)
=========================================================
ALL service port assignments MUST be read from this module.
No hardcoded port numbers anywhere else in the codebase.

This replaces:
  - app_v6.py _AI_BACKEND_PORTS hardcoded dict
  - gen_service_manifests.py hardcoded AI backend array
  - agents/shared/config.py port references
  - test harness hardcoded ports

Usage:
    from shared.core.service_ports import get_port, get_service_url, AI_BACKENDS

    port = get_port("memory-system")          # → 8009
    url = get_service_url("cv-processor")     # → "http://cv-processor:8020"
    port = get_port("gamification-service")   # → 8000 (default for generated services)
"""

# ── AI Backend Services (12 services with dedicated ports) ──────────────
# These run on custom ports (not 8000) because they're hand-written
# services in shared/ with their own Uvicorn entrypoints.
AI_BACKENDS: dict[str, dict] = {
    # Consciousness layer (shared/consciousness/)
    "memory-system":       {"port": 8009, "source": "shared/consciousness/memory_system",      "category": "consciousness"},
    "learning-system":     {"port": 8010, "source": "shared/consciousness/learning_system",    "category": "consciousness"},
    "pattern-recognition": {"port": 8011, "source": "shared/consciousness/pattern_recognition", "category": "consciousness"},
    "decision-making":     {"port": 8012, "source": "shared/consciousness/decision_making",    "category": "consciousness"},

    # Extended layer (shared/extended/)
    "career-navigator":    {"port": 8017, "source": "shared/extended/career_navigator",  "category": "extended"},
    "skill-bridge":        {"port": 8018, "source": "shared/extended/skill_bridge",      "category": "extended"},
    "job-matcher":          {"port": 8019, "source": "shared/extended/job_matcher",       "category": "extended"},
    "cv-processor":        {"port": 8020, "source": "shared/extended/cv_processor",      "category": "extended"},

    # AI layer (shared/ai/)
    "gpt4-orchestrator":   {"port": 8032, "source": "shared/ai/gpt4_orchestrator",     "category": "ai"},
    "claude-integration":  {"port": 8033, "source": "shared/ai/claude_integration",    "category": "ai"},
    "embeddings-engine":   {"port": 8034, "source": "shared/ai/embeddings_engine",     "category": "ai"},
    "vector-store":        {"port": 8035, "source": "shared/ai/vector_store",          "category": "ai"},
}

# ── Default port for generated factory services (219 services) ──────────
# All services generated by the Service Engine listen on port 8000
# unless overridden by SERVICE_PORT environment variable.
DEFAULT_SERVICE_PORT = 8000

# ── Gateway port ────────────────────────────────────────────────────────
GATEWAY_PORT = 5000


def get_port(service_dns: str) -> int:
    """Get the port for a service by its K8s DNS name.

    AI backends return their dedicated port (8009-8035).
    All other services return 8000 (the factory default).

    Args:
        service_dns: K8s service name (e.g., "memory-system", "gamification-service")

    Returns:
        Port number
    """
    backend = AI_BACKENDS.get(service_dns)
    if backend:
        return backend["port"]
    return DEFAULT_SERVICE_PORT


def get_service_url(service_dns: str) -> str:
    """Get the full internal URL for a service.

    Args:
        service_dns: K8s service name

    Returns:
        URL like "http://memory-system:8009"
    """
    return f"http://{service_dns}:{get_port(service_dns)}"


def get_ai_backend_ports() -> dict[str, int]:
    """Get the port map for all AI backends (for gateway _AI_BACKEND_PORTS).

    Returns:
        {"memory-system": 8009, "cv-processor": 8020, ...}
    """
    return {name: info["port"] for name, info in AI_BACKENDS.items()}


def get_ai_backend_manifests() -> list[dict]:
    """Get AI backend definitions for K8s manifest generation.

    Returns:
        [{"name": "memory_system", "dns": "memory-system", "port": 8009, "source": "shared/..."}, ...]
    """
    return [
        {
            "name": dns.replace("-", "_"),
            "dns": dns,
            "port": info["port"],
            "source": info["source"],
        }
        for dns, info in AI_BACKENDS.items()
    ]
